name: authentication
description: A new Flutter project.

publish_to: 'none' #

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_svg: ^1.1.6
  get_it: ^7.2.0 
  internet_connection_checker: ^0.0.1+4
  dio: ^4.0.6
  flutter_riverpod: ^2.3.0
  riverpod: ^2.3.0
  flutter_native_splash: ^2.2.17 
  firebase_core: ^2.6.1
  firebase_auth: ^4.2.10
  google_sign_in: ^6.0.2
  flutter_facebook_auth: ^5.0.8

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/watermelon.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/images/

  fonts:
   - family: Urbanist
     fonts:
       - asset: assets/fonts/Urbanist-VariableFont_wght.ttf
  
  

