// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNI5YcaVx8V32Xz0OVFN9uQcMaGQtlOFg',
    appId: '1:799641977800:web:166738026c671e70e1f6fd',
    messagingSenderId: '799641977800',
    projectId: 'authentication-365e9',
    authDomain: 'authentication-365e9.firebaseapp.com',
    storageBucket: 'authentication-365e9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMn04mY9Tul_eUuiR3N5pyCyZPo91NX_g',
    appId: '1:799641977800:android:4f5af3411e431621e1f6fd',
    messagingSenderId: '799641977800',
    projectId: 'authentication-365e9',
    storageBucket: 'authentication-365e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC01dRpRzq6L0OsC5wNLc1ONU96pyE66pE',
    appId: '1:799641977800:ios:87ef48561eab2d4ae1f6fd',
    messagingSenderId: '799641977800',
    projectId: 'authentication-365e9',
    storageBucket: 'authentication-365e9.appspot.com',
    androidClientId: '799641977800-hd1erts2m4tfpc9h7ks6drpbifb4m5am.apps.googleusercontent.com',
    iosClientId: '799641977800-qid40pmlr65ka855cl75t1mv2gsucsta.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC01dRpRzq6L0OsC5wNLc1ONU96pyE66pE',
    appId: '1:799641977800:ios:87ef48561eab2d4ae1f6fd',
    messagingSenderId: '799641977800',
    projectId: 'authentication-365e9',
    storageBucket: 'authentication-365e9.appspot.com',
    androidClientId: '799641977800-hd1erts2m4tfpc9h7ks6drpbifb4m5am.apps.googleusercontent.com',
    iosClientId: '799641977800-qid40pmlr65ka855cl75t1mv2gsucsta.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentication',
  );
}
